server:
  port: 9001
  
spring:
  application: 
    name: user-service
  
  eureka:
    instance:
     hostname:localhost
       data:    mongodb:      database: userdb
        mongodb.port=27017
          mongo.user=root
            mongodb.password=root